version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: swepostgres
    ports:
      - '5432:5432'
    volumes:
      - psql-data:/data/db
    environment:
      POSTGRES_URI: ${DATABASE_URL}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SERVER_PORT: 9443

  server:
    build:
      context: src/backend
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '9443:9443'
    depends_on:
      - postgres

volumes:
  psql-data: