version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: swepostgres
    ports:
      - '5432:5432'
    volumes:
      - psql-data:/data/db
    environment:
      #      POSTGRES_URI: postgres://postgres:password@localhost/SWEDatabase
      POSTGRES_PASSWORD: password
  #      SERVER_PORT: 9443
  #      POSTGRES_HOST: localhost

  server:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '9443:9443'
    depends_on:
      - postgres
    environment:
      POSTGRES_URI: postgres://postgres:password@localhost/SWEDatabase
      CORS_URL: https://localhost:9443
      CORS_ENDING_URL: /api/v1

volumes:
  psql-data: