version: '4.3'

services:
  postgres:
    image: postgres:latest
    container_name: swepostgres
    ports:
      - '5432:5432'
    volumes:
      - psql-data:/data/db
    environment:
      #      POSTGRES_URI: postgres://postgres:password@localhost/SWEDatabase
      POSTGRES_PASSWORD: password
      POSTGRES_DB: SWEDatabase
  #      SERVER_PORT: 9443
  #      POSTGRES_HOST: localhost

  server:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    container_name: servers
    ports:
      - '9443:9443'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/SWEDatabase
      CORS_URL: http://localhost:3000
      CORS_ENDING_URL: /api/v1

volumes:
  psql-data: