version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: swepostgres
    ports:
      - '5432:5432'
    volumes:
      - psql-data:/data/db

  server:
    build:
      context: src/backend
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    environment:
      POSTGRES_URI: postgres://danielkaplan:password@localhost/SWEDatabase
#      ${DATABASE_URL}
      POSTGRES_PASSWORD: password
#      ${POSTGRES_PASSWORD}
      SERVER_PORT: 5000

volumes:
  psql-data: